---
Name: webpimages
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Assets\Flysystem\PublicAdapter:
    class: TheWebmen\WebpImages\Flysystem\PublicAssetAdapter
  SilverStripe\Assets\Flysystem\ProtectedAdapter:
    class: TheWebmen\WebpImages\Flysystem\ProtectedAssetAdapter

SilverStripe\Assets\Storage\DBFile:
  extensions:
    - TheWebmen\WebpImages\Storage\DBFileExtension

SilverStripe\Assets\File:
  allowed_extensions:
    - webp

Silverstripe\Assets\Image:
  extensions:
    - TheWebmen\WebpImages\Asset\ImageExtension
